tickers_brut = {
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc. (Class A)",
    "AMZN": "Amazon.com Inc.",
    "TSLA": "Tesla Inc.",
    "META": "Meta Platforms Inc.",
    "NVDA": "NVIDIA Corporation",
    "BRK-A": "Berkshire Hathaway Inc. (Class A)",
    "JPM": "JPMorgan Chase & Co.",
    "V": "Visa Inc.",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart Inc.",
    "PG": "Procter & Gamble Co.",
    "UNH": "UnitedHealth Group Incorporated",
    "M": "Mastercard Incorporated",
    "DIS": "The Walt Disney Company",
    "HD": "The Home Depot Inc.",
    "BAC": "Bank of America Corporation",
    "XOM": "Exxon Mobil Corporation",
    "PFE": "Pfizer Inc.",
    "KO": "The Coca-Cola Company",
    "PEP": "PepsiCo Inc.",
    "CSCO": "Cisco Systems Inc.",
    "ADBE": "Adobe Inc.",
    "NFLX": "Netflix Inc.",
    "CMCSA": "Comcast Corporation",
    "NKE": "Nike Inc.",
    "ABT": "Abbott Laboratories",
    "T": "AT&T Inc.",
    "CRM": "Salesforce Inc.",
    "ORCL": "Oracle Corporation",
    "COST": "Costco Wholesale Corporation",
    "VZ": "Verizon Communications Inc.",
    "MRK": "Merck & Co., Inc.",
    "LLY": "Eli Lilly and Company",
    "INTC": "Intel Corporation",
    "CCI": "Crown Castle Inc.",
    "KR": "The Kroger Co.",
    "WBA": "Walgreens Boots Alliance Inc.",
    "BIIB": "Biogen Inc.",
    "BMY": "Bristol-Myers Squibb Company",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "GILD": "Gilead Sciences Inc.",
    "EW": "Edwards Lifesciences Corporation",
    "ILMN": "Illumina Inc.",
    "ALGN": "Align Technology Inc.",
    "IQV": "IQVIA Holdings Inc.",
    "A": "Agilent Technologies Inc.",
    "D": "Dominion Energy Inc.",
    "ET": "Energy Transfer LP",
    "OKE": "ONEOK Inc.",
    "EPD": "Enterprise Products Partners L.P.",
    "KMI": "Kinder Morgan Inc.",
    "COP": "ConocoPhillips",
    "PSX": "Phillips 66",
    "EOG": "EOG Resources Inc.",
    "SLB": "Schlumberger Limited",
    "HAL": "Halliburton Company",
    "BKR": "Baker Hughes Company",
    "APA": "APA Corporation",
    "OXY": "Occidental Petroleum Corporation",
    "WMB": "The Williams Companies Inc.",
    "DTE": "DTE Energy Company",
    "AEE": "Ameren Corporation",
    "ES": "Eversource Energy",
    "CMS": "CMS Energy Corporation",
    "NI": "NiSource Inc.",
    "PCG": "PG&E Corporation",
    "SRE": "Sempra",
    "XEL": "Xcel Energy Inc.",
    "EIX": "Edison International",
    "VTR": "Ventas Inc.",
    "WELL": "Welltower Inc.",
    "ARE": "Alexandria Real Estate Equities Inc.",
    "HCA": "HCA Healthcare Inc.",
    "UHS": "Universal Health Services Inc.",
    "DGX": "Quest Diagnostics Incorporated",
    "LH": "Laboratory Corporation of America Holdings",
    "DVA": "DaVita Inc."}


full_categories_dict = {
    "AAPL": "Equity",
    "MSFT": "Equity",
    "GOOGL": "Equity",
    "AMZN": "Equity",
    "TSLA": "Equity",
    "META": "Equity",
    "NVDA": "Equity",
    "BRK-A": "Equity",
    "JPM": "Equity",
    "V": "Equity",
    "JNJ": "Equity",
    "WMT": "Equity",
    "PG": "Equity",
    "UNH": "Equity",
    "MA": "Equity",
    "DIS": "Equity",
    "HD": "Equity",
    "BAC": "Equity",
    "XOM": "Equity",
    "PFE": "Equity",
    "KO": "Equity",
    "PEP": "Equity",
    "CSCO": "Equity",
    "ADBE": "Equity",
    "NFLX": "Equity",
    "CMCSA": "Equity",
    "NKE": "Equity",
    "ABT": "Equity",
    "T": "Equity",
    "CRM": "Equity",
    "ORCL": "Equity",
    "COST": "Equity",
    "VZ": "Equity",
    "MRK": "Equity",
    "LLY": "Equity",
    "INTC": "Equity",
    "CCI": "Equity",
    "KR": "Equity",
    "WBA": "Equity",
    "BIIB": "Equity",
    "BMY": "Equity",
    "VRTX": "Equity",
    "GILD": "Equity",
    "EW": "Equity",
    "ILMN": "Equity",
    "ALGN": "Equity",
    "IQV": "Equity",
    "A": "Equity",
    "D": "Equity",
    "ET": "Equity",
    "OKE": "Equity",
    "EPD": "Equity",
    "KMI": "Equity",
    "COP": "Equity",
    "PSX": "Equity",
    "EOG": "Equity",
    "SLB": "Equity",
    "HAL": "Equity",
    "BKR": "Equity",
    "APA": "Equity",
    "OXY": "Equity",
    "WMB": "Equity",
    "DTE": "Equity",
    "AEE": "Equity",
    "ES": "Equity",
    "CMS": "Equity",
    "NI": "Equity",
    "PCG": "Equity",
    "SRE": "Equity",
    "XEL": "Equity",
    "EIX": "Equity",
    "VTR": "Equity",
    "WELL": "Equity",
    "ARE": "Equity",
    "HCA": "Equity",
    "UHS": "Equity",
    "DGX": "Equity",
    "LH": "Equity",
    "DVA": "Equity",
    "ZN=F": "Bond",
    "ZF=F": "Bond",
    "ZT=F": "Bond",
    "ZB=F": "Bond",
    "ZO=F": "Bond",
    "BZ=F": "Commodities",
    "NG=F": "Commodities",
    "RB=F": "Commodities",
    "HO=F": "Commodities",
    "GC=F": "Commodities",
    "SI=F": "Commodities",
    "HG=F": "Commodities",
    "PL=F": "Commodities",
    "PA=F": "Commodities",
    "ZC=F": "Commodities",
    "ZS=F": "Commodities",
    "ZW=F": "Commodities",
    "KC=F": "Commodities",
    "CT=F": "Commodities",
    "SB=F": "Commodities",
    "CC=F": "Commodities",
    "LE=F": "Commodities",
    "GF=F": "Commodities",
    "HE=F": "Commodities",
    "OJ=F": "Commodities",
    "BTC-USD": "Crypto",
    "ETH-USD": "Crypto",
    "BNB-USD": "Crypto",
    "XRP-USD": "Crypto",
    "ADA-USD": "Crypto",
    "SOL-USD": "Crypto",
    "MATIC-USD": "Crypto",
    "SHIB-USD": "Crypto",
    "LTC-USD": "Crypto",
    "AVAX-USD": "Crypto",
    "LINK-USD": "Crypto",
    "XLM-USD": "Crypto",
    "ATOM-USD": "Crypto",
    "TRX-USD": "Crypto",
    "ETC-USD": "Crypto",
    "AXS-USD": "Crypto",
    "FTM-USD": "Crypto",
    "VET-USD": "Crypto",
    "THETA-USD": "Crypto",
    "XTZ-USD": "Crypto",
    "ENJ-USD": "Crypto",
    "QNT-USD": "Crypto",
    "LDO-USD": "Crypto",
    "BAT-USD": "Crypto",
    "YFI-USD": "Crypto",
}